In [1]:
#dependencies

import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

In [2]:
#importing csv file

lend = pd.read_csv('../Resources/lending_data.csv')
lend.head(10)

,loan_size,interest_rate,borrower_income,debt_to_income,num_of_accounts,derogatory_marks,total_debt,loan_status
0,10700.0,7.672,52800,0.431818,5,1,22800,0
1,8400.0,6.692,43600,0.311927,3,0,13600,0
2,9000.0,6.963,46100,0.349241,3,0,16100,0
3,10700.0,7.664,52700,0.430740,5,1,22700,0
4,10800.0,7.698,53000,0.433962,5,1,23000,0
5,10100.0,7.438,50600,0.407115,4,1,20600,0
6,10300.0,7.490,51100,0.412916,4,1,21100,0
7,8800.0,6.857,45100,0.334812,3,0,15100,0
8,9300.0,7.096,47400,0.367089,3,0,17400,0
9,9700.0,7.248,48800,0.385246,4,0,18800,0

In [3]:
#declaring X & y variables

X = lend.drop("loan_status", axis=1)
y = lend['loan_status']

In [4]:
#preparing the data

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [5]:
#fitting the model

lend_rf = RandomForestClassifier(random_state=42).fit(X_train_scaled, y_train)
y_pred = lend_rf.predict(X_test_scaled)

In [6]:
#scoring the model and printing a classification report

print(classification_report(y_test, y_pred))
print(f'Training Score: {lend_rf.score(X_train_scaled, y_train)}')
print(f'Testing Score: {lend_rf.score(X_test_scaled, y_test)}')

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18792
           1       0.84      0.90      0.87       592

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.93     19384
weighted avg       0.99      0.99      0.99     19384

Training Score: 0.9971798046498831
Testing Score: 0.9917457697069748

The scores for both models are .99 and above, but I still believe that the Random Forest Classifier model better explains the data. This is because the variables do not have a linear relationship, which makes me question why we are recieving such a high testing score with the Logistic Regression model.